### ISSUE TITLE
Error missing closing '}' in statement block in RunSDDC.ps1

### ISSUE THREAD

**Issue by TommyPaulkDell** [DellProSupportGse/Tools#11]
When running RunSDDC.ps1 on an Azure HCI cluster we receive this warning:

WARNING: 2022-09-19T13:20:54 : 'Invoke-Command -ComputerName xxxxxxxxxxxx {Echo Get-mpioSettings;Get-ItemProperty -path
"HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e97b-e325-11ce-bfc1-08002be10318}\000*"' failed for node xxxxxxxxxxxxxxxxxxxx (At line:1 char:45
+ Invoke-Command -ComputerName xxxxxxxxxxx {Echo Get-mpioSettings;Ge ...
+                                             ~
Missing closing '}' in statement block or type definition.)
WARNING: 2022-09-19T13:20:54 : 'Get-MSDSMSupportedHW  -CimSession xxxxxxxxxxx' failed for node xxxxxxxxxxxxxxxxxxxx  (The term 'Get-MSDSMSupportedHW' is not
recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.)

**Comment by DellProSupportGse** [comment]
Resolved
