### ISSUE TITLE
Option to not create scheduled task for DART pre-restart

### ISSUE THREAD

**Issue by NikStayCMNH** [DellProSupportGse/Tools#13]
This tool is fantastic! I love how easy it is to use. Thanks for your time building something like this that addresses a real need. We have Windows Admin Center with the Dell Open Manage Integration and that has been really frustrating to use, so I'm glad there is something like this that is a little more reliable. 

I have only run into a few problems and they are usually around bringing nodes back online and putting disks into and out of maintenance mode. 

I am pretty new to clustered server management, so I may just be missing key steps of how the process works or best practices. So if these wouldn't actually be helpful, I'd love feedback on what I may be missing.

### Pre-Dart Run
Pre-run isn't too hard and is where I run into the least amount of problems. I can pause a node before I run the tool and manually put the disks in Maintenance Mode if I really want to.

### Post-Dart Run
Most of the problems I have are after the node comes back online. It feels like the node gets brought back online before the disks are out of maintenance mode. And if there is a problem with bringing a disk back online I've been having issues with Roles being paused due to the missing disks.

Would it be possible to make the scheduled task that gets made on a node optional? That way I could make sure disks are out of maintenance mode and good to go before bringing the node back online. I also tend to run this task via remote PowerShell so having to log in to bring a node back online is not my favorite. I'm trying to get rid of RDP to critical infrastructure like Nodes, so having an alternative that I can run remotely would be nice. 

I don't know if having the scheduled task actually affects anything if I just ignored it and manually brought the node back online remotely and logged in and it ran at a later date, so again, smarter people than me might just know how to get around it.

**Comment by DellProSupportGse** [comment]
Thank you very much for the positive feedback. You would be surprised at how little that ever happens.  :)

It is true you can disable SMM before you resume a node in 2016/2019 but MSFT changed the process for 2022/HCIOS so you have to resume the node first and then you can disable SMM. I suspect this is how MSFT wants the process to be performed.

**Comment by TommyPaulkDell** [comment]
Hey NikStayCMNH,
We just committed some updated code today to DART, so check it out.
Also, if you apply updates and need a reboot, hit N and it will NOT create the schedule task.
If no updates are needed, then hitting Y will run the commands immediately and also NOT create the schedule task.
We really appreciate that you are enjoying these scripts.

**Comment by NikStayCMNH** [comment]
@DellProSupportGse Thanks for taking the time to educate me, I am glad there are people like you that take the time to really learn this and then create tools that make the process easier for those of us who haven't gotten there yet or don't have the time to get there!
@TommyPaulkDell  I appreciate the update and the specifics about what options there are!
