### ISSUE TITLE
Omit error messages for non existing items

### ISSUE THREAD

**Issue by Karl-WE** [DellProSupportGse/Tools#16]
The Script throws errors for missing NIC Marvell Performance counters

Missing MPIO registry settings (as no MPIO is needed for S2D / Azure Stack HCI).

Proposal:
These errors should result into Informational output and be logged internally for instance if expected. Otherwise Out-Null or -ErrorAction SilentyContinue

1.1.37 PrivateCloud.DiagnosticInfo

**Comment by TommyPaulkDell** [comment]
Thanks for the suggestion. It has been added to the latest version of the SDDC capture.

**Comment by Karl-WE** [comment]
You're welcome! I am going ahead and closing this PR.
