### ISSUE TITLE
SDDC v1.21 Fails on Server 2016 Datacenter

### ISSUE THREAD

**Issue by BEEGUY1337** [DellProSupportGse/Tools#23]
When executing an SDDC via the Toolbox v1.1 on Server 2016 Datacenter, the process fails at "Phase 4 - Compacting files for transport" with the following error:

```
Show-Error : 2023-06-29T13:36:54 : Error creating the ZIP file!
Content remains available at C:\Users\XXXX\HealthTest\ - cmdlet was cancelled
At C:\Program Files\WindowsPowerShell\Modules\PrivateCloud.DiagnosticInfo\PrivateCloud.DiagnosticInfo.psm1:3429 char:9
+         Show-Error("Error creating the ZIP file!`nContent remains ava ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Show-Error
```

This process has been attempted on multiple Server 2016 Datacenter nodes with the same result. Running SDDC v1.21 on Server 2019 Datacenter results in no errors.

At this time, we're unable to generate SDDCs for Server 2016 deployments.

**Comment by DellProSupportGse** [comment]
Can you help me understand where you got SDDC v1.21? We are currently on v1.1.37

**Comment by BEEGUY1337** [comment]
I'm referencing the version that displays when creating an SDDC. Below are the steps to reproduce and a screenshot for reference:

1. Select option "5) Log Collector"
2. Load "Log Collector"
3. Select option "1) Azure Stack HCI/S2D logs (SDDC)"
4. Version in the corner says "v1.21 RunSDDC By: Jim Gandy"


<img width="311" alt="image" src="https://github.com/DellProSupportGse/Tools/assets/138158598/5e2aca5f-0e19-4491-88de-150da967d0a7">

**Comment by TommyPaulkDell** [comment]
That does help. That part of the code is from the Microsoft portion of this tool. Can you try to run the primary code base from https://github.com/PowerShell/PrivateCloud.DiagnosticInfo
If you still have this issue, raise it on that repository.

**Comment by BEEGUY1337** [comment]
You are correct. There is an issue with the Microsoft portion of the tool. I will submit a bug report there. Thank you.
