### ISSUE TITLE
-IgnoreChecks:$True not working

### ISSUE THREAD

**Issue by ekrizon** [DellProSupportGse/Tools#24]
Long story short we had windows updates hang on us and had to reboot the node and get it happy. Since it was already paused/disks in maint mode we wanted to run Dart to do drivers/firmware but -IgnoreChecks:$True was not working. 

Upon running with -IgnoreChecks:$True appended nothing appeared different, script still complained node was down and disks were unhealthy and exited

**Comment by DellProSupportGse** [comment]
Would you please include the DART transcript log for further analyses? Its located in C:\ProgramData\Dell\DART

**Comment by ekrizon** [comment]
**********************
Windows PowerShell transcript start
Start time: 20230629180636
Username: EDUC\Curtis J Kutzan
RunAs User: EDUC\Curtis J Kutzan
Configuration Name: 
Machine: HCI-01-N01 (Microsoft Windows NT 10.0.17763.0)
Host Application: C:\Windows\system32\WindowsPowerShell\v1.0\PowerShell_ISE.exe
Process ID: 15384
PSVersion: 5.1.17763.3770
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.3770
BuildVersion: 10.0.17763.3770
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\programdata\Dell\DART\DART_20230629_180636.log
Logging Telemetry Information...
1.45
 __        __  ___ 
|  \  /\  |__)  |  
|__/ /~~\ |  \  |

This code is provided as-is and is not supported by Dell Technologies

==================== Please make a selection =====================

Press '1' to Install Windows Updates
Press '2' to Install Dell Drivers and Firmware
Press '3' to Install Windows Updates and Dell Drivers and Firmware
Press 'H' to Display Help
Press 'Q' to Quit

Installing Dell Drivers and Firmware...
Finding Latest Dell System Update(DSU) version...
    Found: 2.0.2.0 | https://downloads.dell.com/omimswac/dsu/Systems-Management_Application_RWVV0_WN64_2.0.2.0_A00.EXE
Checking if DSU is installed...
    FOUND: DSU 2.0.2.0 already installed
Gather Server Model Info...
WARNING: 2023/06/29-18:06:44.791 Node 'HCI-01-N01' is not up
    SUCCESS: AX-640
Downloading Catalog...
    Downloading https://downloads.dell.com/catalog/ASHCI-Catalog.xml.gz...
        SUCCESS: File downloaded successfully
Expanding Catalog for use...
    SUCCESS: Catalog expanded
Executing S2D/Azure Stack HCI Pre-Checks...
    ERROR: Virtual Disk(s) UnHealth Please remediate before continuing
**********************
Windows PowerShell transcript end
End time: 20230629180645
**********************

**Comment by TommyPaulkDell** [comment]
I see. 
We never intended to have it run from ISE. It will work if you add the parameter to the invoke line to run DART. I will put in a change though to allow it to work when running the PS1 directly.
Thanks,
Tommy Paulk

**Comment by TommyPaulkDell** [comment]
I have added the change. Have you been able to check it?

**Comment by ekrizon** [comment]
fixed, thanks!
