### ISSUE TITLE
[DART] ERROR: Failed to find DSU version. Exiting... /   Server Error 403 - Forbidden: Access is denied.

### ISSUE THREAD

**Issue by chrisloup** [DellProSupportGse/Tools#37]
I'm trying to update 4 azure stack hci nodes ax640 .
first 2 nodes ran without issue. node 3 and 4 came out with this error. 
node 3 after 2hours, i ran the same dart commands and it ran successfully.
node 4 is still showing the same error.

dart version appears to be 1.47
Please make a selection: 2
Installing Dell Drivers and Firmware...
Finding Latest Dell System Update(DSU) version...
    ERROR: Failed to find DSU version. Exiting...
Transcript stopped, output file is C:\programdata\Dell\DART\DART_20240117_144220.log

--transcript shows a 403 error--- (so some server side latency/capacity issues?)---

Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noExit -Command Invoke-SConfigLogon
Process ID: 12848
PSVersion: 5.1.20348.2227
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.20348.2227
BuildVersion: 10.0.20348.2227
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\programdata\Dell\DART\DART_20240117_144220.log
Logging Telemetry Information...
1.47
 __        __  ___ 
|  \  /\  |__)  |  
|__/ /~~\ |  \  |

This code is provided as-is and is not supported by Dell Technologies

==================== Please make a selection =====================

Press '1' to Install Windows Updates
Press '2' to Install Dell Drivers and Firmware
Press '3' to Install Windows Updates and Dell Drivers and Firmware
Press 'H' to Display Help
Press 'Q' to Quit

Installing Dell Drivers and Firmware...
Finding Latest Dell System Update(DSU) version...
PS>TerminatingError(Invoke-WebRequest): "

403 - Forbidden: Access is denied.

Server Error

 
  403 - Forbidden: Access is denied.
  You do not have permission to view this directory or page using the credentials that you supplied.
 

"
    ERROR: Failed to find DSU version. Exiting...
**********************

**Comment by chrisloup** [comment]
https://downloads.dell.com/omimswac/dsu/ basically is causing the error

**Comment by vusd-adam** [comment]
I'm having similar issues with dart. Getting access denied when it's trying to download DSU or SMA.

**********************
Windows PowerShell transcript start
Start time: 20240117152001
Configuration Name: 
Machine: (Microsoft Windows NT 10.0.17763.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell_ise.exe C:\data\scripts\dart.ps1
Process ID: 6652
PSVersion: 5.1.17763.5328
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.5328
BuildVersion: 10.0.17763.5328
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\programdata\Dell\DART\DART_20240117_152001.log
Logging Telemetry Information...
1.47
 __        __  ___ 
|  \  /\  |__)  |  
|__/ /~~\ |  \  |

This code is provided as-is and is not supported by Dell Technologies

==================== Please make a selection =====================

Press '1' to Install Windows Updates
Press '2' to Install Dell Drivers and Firmware
Press '3' to Install Windows Updates and Dell Drivers and Firmware
Press 'H' to Display Help
Press 'Q' to Quit

Installing Dell Drivers and Firmware...
Downloading Dell System Update(DSU)...
    Downloading https://dl.dell.com/FOLDER10889507M/1/Systems-Management_Application_RPW7K_WN64_2.0.2.3_A00.EXE...
PS>TerminatingError(Invoke-WebRequest): "Access Denied
You don't have permission to access "http://dl.dell.com/FOLDER10889507M/1/Systems-Management_Application_RPW7K_WN64_2.0.2.3_A00.EXE" on this server.
Reference #18.c6017c68.1705533604.1659789f"
        ERROR: Downloading https://dl.dell.com/FOLDER10889507M/1/Systems-Management_Application_RPW7K_WN64_2.0.2.3_A00.EXE
**********************
Windows PowerShell transcript end
End time: 20240117152004
**********************

**Comment by chrisloup** [comment]
yes, issue is dell webservers, maybe someone changed some permissions

this morning I tried the dart commands again. so it got along further

Installing Dell Drivers and Firmware...
Downloading Dell System Update(DSU)...
    Downloading https://dl.dell.com/FOLDER10889507M/1/Systems-Management_Application_RPW7K_WN64_2.0.2.3_A00.EXE...
PS>TerminatingError(Invoke-WebRequest): "<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;dl&#46;dell&#46;com&#47;FOLDER10889507M&#47;1&#47;Systems&#45;Management&#95;Application&#95;RPW7K&#95;WN64&#95;2&#46;0&#46;2&#46;3&#95;A00&#46;EXE" on this server.<P>
Reference&#32;&#35;18&#46;c9962a17&#46;1705546419&#46;3422dae
</BODY>
</HTML>
"
        ERROR: Downloading https://dl.dell.com/FOLDER10889507M/1/Systems-Management_Application_RPW7K_WN64_2.0.2.3_A00.EXE

**Comment by chrisloup** [comment]
the two links above I can download on my pc. I suspect dart is being blocked or anonymous access/or user agent is being blocked by dell?
--
my support ticket to dell also got this response
"As I checked with our SE, DART is not supported by Dell Support. Please review the DART disclaimer in the script, "This code is provided as-is and is not supported by Dell Technologies".

For this Dart Tool issue Dell is unable to assist but you may refer to page 76 for Firmware and driver updates for your reference."

**Comment by chrisloup** [comment]
I've managed to perform updates using idrac integration + dell repository manager, (ie: the files are being downloaded). so i suspect dell might have blocked dart or block certain user agents of some kind

**Comment by chrisloup** [comment]
might be an intermittent issue. I just ran dart successfully.

**Comment by TommyPaulkDell** [comment]
Sorry we didn't comment earlier. We changed DART to download the direct version. We are planning on updating it to find the latest at some point in the future.
